# ---------- Build stage ----------
FROM node:latest as build
WORKDIR /app

# Copy the package.json file
COPY package*.json ./
# Run a clean install of dependencies
RUN npm ci
# Install Angular CLI
RUN npm install -g @angular/cli
# Copy source and build
COPY . .
# Build the application
RUN npm run build --configuration:production

# ---------- Production stage ----------
FROM nginx:latest

# Remove default nginx website
RUN rm -rf /usr/share/nginx/html/*

# Copy the build output to replace the default nginx contents
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

# Copy build output to replace default nginx contents
COPY --from=build /app/dist/meet-portfolio/browser /usr/share/nginx/html


EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]