/**
 * Mock Chat Server for Development
 * 
 * This file provides mock implementations for both HTTP and WebSocket chat endpoints.
 * Use this for local development when the real backend is not available.
 * 
 * Usage:
 * 1. HTTP: Set CHAT_MOCK=true in environment and use the mock HTTP endpoint
 * 2. WebSocket: Run the WebSocket mock server separately (see instructions below)
 */

import { Injectable } from '@angular/core';
import { Observable, of, throwError, timer } from 'rxjs';
import { delay, map } from 'rxjs/operators';
import { Message, ChatRequest, ChatResponse, ChatStreamDelta } from './chat.types';

/**
 * Mock HTTP Chat Service
 * Simulates HTTP POST /api/chat with optional streaming
 */
@Injectable({
  providedIn: 'root',
})
export class MockChatServer {
  private messageHistory: Message[] = [];

  /**
   * Simulate HTTP chat request
   */
  mockHttpChat(request: ChatRequest): Observable<ChatResponse> {
    // Simulate network delay
    return timer(Math.random() * 500 + 200).pipe(
      map(() => {
        const userMessage = request.messages[request.messages.length - 1];
        const assistantMessage: Message = {
          id: `msg_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
          role: 'assistant',
          content: this.generateMockResponse(userMessage.content),
          createdAt: new Date().toISOString(),
          status: 'delivered',
        };

        this.messageHistory.push(userMessage, assistantMessage);

        return {
          message: assistantMessage,
          sessionId: request.sessionId,
        };
      })
    );
  }

  /**
   * Simulate HTTP streaming chat (SSE)
   */
  mockHttpChatStream(request: ChatRequest): Observable<ChatStreamDelta> {
    const userMessage = request.messages[request.messages.length - 1];
    const fullResponse = this.generateMockResponse(userMessage.content);
    const words = fullResponse.split(' ');
    let currentIndex = 0;

    return new Observable<ChatStreamDelta>((observer) => {
      const interval = setInterval(() => {
        if (currentIndex < words.length) {
          const delta = (currentIndex === 0 ? '' : ' ') + words[currentIndex];
          observer.next({
            delta,
            complete: false,
            messageId: `msg_${Date.now()}`,
          });
          currentIndex++;
        } else {
          observer.next({
            delta: '',
            complete: true,
            messageId: `msg_${Date.now()}`,
          });
          observer.complete();
          clearInterval(interval);
        }
      }, 50); // Simulate typing speed

      return () => clearInterval(interval);
    });
  }

  /**
   * Generate mock response based on user input
   */
  private generateMockResponse(userInput: string): string {
    const lowerInput = userInput.toLowerCase();

    if (lowerInput.includes('hello') || lowerInput.includes('hi')) {
      return 'Hello! How can I help you today?';
    }

    if (lowerInput.includes('help')) {
      return 'I\'m here to help! You can ask me questions, and I\'ll do my best to assist you.';
    }

    if (lowerInput.includes('weather')) {
      return 'I don\'t have access to real-time weather data, but I can help you with other questions!';
    }

    if (lowerInput.includes('time')) {
      return `The current time is ${new Date().toLocaleTimeString()}.`;
    }

    if (lowerInput.includes('name')) {
      return 'I\'m a chat assistant. You can call me Assistant!';
    }

    // Default response
    return `I understand you said: "${userInput}". This is a mock response. In a real implementation, this would be generated by an AI model or backend service.`;
  }

  /**
   * Simulate error response
   */
  mockError(): Observable<never> {
    return throwError(() => new Error('Mock server error: Simulated network failure'));
  }
}

/**
 * WebSocket Mock Server (Node.js)
 * 
 * To use this, create a separate Node.js file and run it:
 * 
 * npm install ws @types/ws
 * 
 * Then create a file: mock-websocket-server.js
 * 
 * ```javascript
 * const WebSocket = require('ws');
 * 
 * const wss = new WebSocket.Server({ port: 8080 });
 * 
 * wss.on('connection', (ws) => {
 *   console.log('Client connected');
 * 
 *   ws.on('message', (data) => {
 *     try {
 *       const message = JSON.parse(data.toString());
 *       
 *       if (message.type === 'send') {
 *         const userMessage = message.messages[message.messages.length - 1];
 *         const response = generateMockResponse(userMessage.content);
 *         
 *         // Simulate streaming response
 *         const words = response.split(' ');
 *         let index = 0;
 *         
 *         const streamInterval = setInterval(() => {
 *           if (index < words.length) {
 *             ws.send(JSON.stringify({
 *               type: 'delta',
 *               delta: (index === 0 ? '' : ' ') + words[index],
 *               complete: false
 *             }));
 *             index++;
 *           } else {
 *             clearInterval(streamInterval);
 *             ws.send(JSON.stringify({
 *               type: 'done',
 *               message: {
 *                 id: `msg_${Date.now()}`,
 *                 role: 'assistant',
 *                 content: response,
 *                 createdAt: new Date().toISOString()
 *               }
 *             }));
 *           }
 *         }, 50);
 *       }
 *     } catch (error) {
 *       ws.send(JSON.stringify({
 *         type: 'error',
 *         error: error.message
 *       }));
 *     }
 *   });
 * 
 *   ws.on('close', () => {
 *     console.log('Client disconnected');
 *   });
 * });
 * 
 * function generateMockResponse(input) {
 *   const lower = input.toLowerCase();
 *   if (lower.includes('hello')) return 'Hello! How can I help?';
 *   if (lower.includes('help')) return 'I\'m here to help!';
 *   return `I understand: "${input}". This is a mock response.`;
 * }
 * 
 * console.log('Mock WebSocket server running on ws://localhost:8080');
 * ```
 * 
 * Run with: node mock-websocket-server.js
 */

/**
 * Environment-based Mock Configuration
 * 
 * In your environment files, you can add:
 * 
 * environment.ts:
 * export const environment = {
 *   production: false,
 *   chatMock: true,
 *   chatEndpoint: '/api/chat',
 *   chatWebSocketUrl: 'ws://localhost:8080/chat'
 * };
 * 
 * Then in your service or component:
 * 
 * if (environment.chatMock) {
 *   // Use mock server
 *   chatService.setConfig({
 *     mode: 'http',
 *     endpoint: '/api/chat-mock'
 *   });
 * }
 */

